@extends('layouts.pharmacy')

@section('page-title', 'Pharmacy Reports')

@section('content')
<div class="d-flex justify-content-between align-items-center mb-3">
    <h2>Pharmacy Reports</h2>
    <a href="{{ route('pharmacy.reports.generate') }}" class="btn btn-primary">
        <i class="fas fa-file-pdf me-1"></i> Generate New Report
    </a>
</div>

@if($reports->isEmpty())
    <div class="alert alert-info">
        <i class="fas fa-info-circle me-2"></i>
        No reports generated yet.
    </div>
@else
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Report Type</th>
                    <th>Period</th>
                    <th>Generated By</th>
                    <th>Generated On</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach($reports as $report)
                <tr>
                    <td>{{ ucfirst($report->report_type) }}</td>
                    <td>
                        @if($report->report_type == 'daily')
                            {{ $report->start_date->format('M j, Y') }}
                        @elseif($report->report_type == 'weekly')
                            {{ $report->start_date->format('M j, Y') }} to {{ $report->end_date->format('M j, Y') }}
                        @elseif($report->report_type == 'monthly')
                            {{ $report->start_date->format('F Y') }}
                        @else
                            {{ $report->start_date->format('M j, Y') }} to {{ $report->end_date->format('M j, Y') }}
                        @endif
                    </td>
                    <td>{{ $report->generated_by }}</td>
                    <td>{{ $report->created_at->format('M j, Y') }}</td>
                    <td>
                        <a href="{{ route('pharmacy.reports.download', $report) }}" class="btn btn-sm btn-outline-primary">
                            <i class="fas fa-download me-1"></i> Download PDF
                        </a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    {{ $reports->links() }}
@endif
@endsection