

<?php $__env->startSection('page-title', 'Pharmacy Reports'); ?>

<?php $__env->startSection('content'); ?>
<div class="d-flex justify-content-between align-items-center mb-3">
    <h2>Pharmacy Reports</h2>
    <a href="<?php echo e(route('pharmacy.reports.generate')); ?>" class="btn btn-primary">
        <i class="fas fa-file-pdf me-1"></i> Generate New Report
    </a>
</div>

<?php if($reports->isEmpty()): ?>
    <div class="alert alert-info">
        <i class="fas fa-info-circle me-2"></i>
        No reports generated yet.
    </div>
<?php else: ?>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Report Type</th>
                    <th>Period</th>
                    <th>Generated By</th>
                    <th>Generated On</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php $__currentLoopData = $reports; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $report): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                <tr>
                    <td><?php echo e(ucfirst($report->report_type)); ?></td>
                    <td>
                        <?php if($report->report_type == 'daily'): ?>
                            <?php echo e($report->start_date->format('M j, Y')); ?>

                        <?php elseif($report->report_type == 'weekly'): ?>
                            <?php echo e($report->start_date->format('M j, Y')); ?> to <?php echo e($report->end_date->format('M j, Y')); ?>

                        <?php elseif($report->report_type == 'monthly'): ?>
                            <?php echo e($report->start_date->format('F Y')); ?>

                        <?php else: ?>
                            <?php echo e($report->start_date->format('M j, Y')); ?> to <?php echo e($report->end_date->format('M j, Y')); ?>

                        <?php endif; ?>
                    </td>
                    <td><?php echo e($report->generated_by); ?></td>
                    <td><?php echo e($report->created_at->format('M j, Y')); ?></td>
                    <td>
                        <a href="<?php echo e(route('pharmacy.reports.download', $report)); ?>" class="btn btn-sm btn-outline-primary">
                            <i class="fas fa-download me-1"></i> Download PDF
                        </a>
                    </td>
                </tr>
                <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
            </tbody>
        </table>
    </div>
    <?php echo e($reports->links()); ?>

<?php endif; ?>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('layouts.pharmacy', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\wamp64\www\EthicalNex\resources\views/pharmacy/reports/index.blade.php ENDPATH**/ ?>